
#Adding to an existing event log does not require admin rights
write-eventlog -LogName "Windows PowerShell" -Source "PowerShell" -EventID 100 -EntryType "Information" -Category 0 -message "hi"

#Adding to a custom Source
#'  [*] Creating an Eventlog and/or an Event source requires adminitrative privileges
#'  [*] Trying to create an Eventlog or Event source that already exists results in an error
#   [*] Creating an Eventlog and/or Event source can be a one time operation if each 
#'       script will use the same Log and Source
#   [*] If admin permissions are easy to have, it can be nice for each script to be listed 
#'       as it's own source.

#Creating a "Log" and a "Source"
$global:EventLogName = "IT Scripts"
$global:EventSourceName = "ScriptName.ps1"
#ACTUAL FOR SCRIPT NAME: $EventSourceName = Split-Path -leaf $MyInvocation.MyCommand.Path

#B
if (-not ([System.Diagnostics.EventLog]::Exists($EventLogName))) {
  new-eventlog -LogName $EventLogName -Source $EventSourceName    
}
#/B
#B
  # Create custom event SOURCE if it does not exist
  if (-not ([System.Diagnostics.EventLog]::SourceExists($EventSourceName))) {
   [System.Diagnostics.EventLog]::CreateEventSource($EventSourceName, $EventLogName)
   }
#/B
#B
  write-eventlog -logname $EventLogName -Source $EventSourceName -EventID 25 -entrytype "Information" -message "Hi again." -category 0
#/B

# Simplified Method: Create custom event SOURCE "PowerShell" in Application log
# To handle tracking which script generated a message without creating a source each time
#' Prepend the script name to each write to the event log.
#B
  if (-not ([System.Diagnostics.EventLog]::SourceExists("PowerShellScripts"))) {
   [System.Diagnostics.EventLog]::CreateEventSource("PowerShellScripts", "Application")
   }
#/B

#Adding to standard "Application" Log
# A benefit to using the application log is that other technicians in your company are likely to 
#'  find your messages even if they haven't been told that scripts are doing event logging.
#B
$global:MsgText = "This is the actual message I want to send."
#$MsgText += "`n`nThis Message Generated By: $(Split-Path -leaf $MyInvocation.MyCommand.Path)"
$global:MsgText += "`n`nThis Message Generated By: $EventSourceName"
write-eventlog -LogName "Application" -Source "PowerShellScripts" -EventID 5 -EntryType "Error" -Category 0 -message $MsgText
#/B